
# ---------------------
# THX Shell # core
# ---------------------
source $HOME/.thx-shell/shell/zsh/zshrc

# ---------------------
# THX Shell # osx
# ---------------------
source $THX_SHELL_HOME/macos/shell/macos-barrel.sh

# SDKMAN must be (?) at the end of the file to work properly
source $THX_SHELL_HOME/shell/zsh/sdkman.sh
